# Generated by Django 2.1.2 on 2018-10-20 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Charpter',
            fields=[
                ('charpter_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('charpter_name', models.CharField(max_length=255)),
                ('charpter_content', models.TextField()),
            ],
            options={
                'db_table': 'charpter',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NovelInfo',
            fields=[
                ('author', models.CharField(max_length=255)),
                ('novel_name', models.CharField(max_length=255)),
                ('read_num', models.IntegerField()),
                ('status', models.CharField(max_length=255)),
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'novel_info',
                'ordering': ['-read_num'],
                'managed': False,
            },
        ),
    ]
